FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install

# The source code will be mounted as a volume in dev
COPY frontend/ .

EXPOSE 3000

CMD ["npm", "run", "dev"]
